### ISSUE TITLE
Fix, typo

### ISSUE THREAD

**Issue by ArkadiK94** [giladfuchs/discord-bot#1]
> channels = [channel for channel in server.text_channels if
                'rojects' in channel.category.name and 'projects-archive' != channel.category.name and channel.name not in EXCLUDE_CHANNELS]

In main file.
Do you have a typo there with the 'rojects '?
Should it be projects 🤔

**Comment by giladfuchs** [comment]
there is P/p rojects so write rojects catch both.

in general, it's only a simple bot to help find unused channel.

**Comment by giladfuchs** [comment]
@ArkadiK94 there is P/p rojects so write rojects catch both.

in general, it's only a simple bot to help find unused channel.
